branch-defaults:
  master:
    environment: objectdetection-env
    group_suffix: null
environment-defaults:
  objectdetection-env:
    branch: null
    repository: null
global:
  application_name: objectdetection
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: C:\Users\dhmodi\PycharmProjects\objectdetection.zip